### ISSUE TITLE
Electron file doesn't exist (Error on Linux)

### ISSUE THREAD

**Issue by elter-tef** [engMaher/LLG-MP#17]
I try to launch LLG-MP on Linux (5.12.15-arch1-1) and when I run `npm run dev-linux` I get the error is presented  below
<pre>
> llg-mp@0.2.4 dev-linux

> nodemon --watch . --exec "./node_modules/electron/dist/electron . --debug" --ext html,js,json,css

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: html,js,json,css
[nodemon] starting `./node_modules/electron/dist/electron . --debug`
sh: line 1: ./node_modules/electron/dist/electron: No such file or directory
[nodemon] failed to start process, "./node_modules/electron/dist/electron . --debug" exec not found
[nodemon] Error
    at Bus.<anonymous> (/home/elter/test/LLG-MP/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:406:35)
    at ChildProcess.<anonymous> (/home/elter/test/LLG-MP/node_modules/nodemon/lib/monitor/run.js:184:11)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
</pre>

**Comment by engMaher** [comment]
As the error indicates, the file in the directory `./node_modules/electron/dist/electron` doesn't exist, did you run `npm install`?

**Comment by elter-tef** [comment]
Of course, I get the following output after the commands:
`npm install electron`
<pre>up to date, audited 1111 packages in 3s

2 packages are looking for funding
  run `npm fund` for details

28 vulnerabilities (4 low, 9 moderate, 13 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
</pre>
`npm run postinstall-linux`
<pre>> llg-mp@0.2.4 postinstall-linux
> npx patch-package && npm install webchimera.js --ignore-scripts && mkdir node_modules/webchimera.js/Release && cp ./wcjs-prebuilt/wcjs_electron_11.1.0_x64_linux/WebChimera.js.node ./node_modules/webchimera.js/Release

npx: installed 50 in 4.579s
patch-package 6.4.7
Applying patches...
computer-sleep@0.0.1 ✔
wcjs-player@6.0.1 ✔
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN llg-mp@0.2.4 No repository field.
npm WARN llg-mp@0.2.4 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webchimera.js@0.2.7
added 2 packages from 1 contributor, removed 2 packages, updated 4 packages and audited 1110 packages in 33.123s

56 packages are looking for funding
  run `npm fund` for details

found 228 vulnerabilities (5 low, 136 moderate, 85 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details</pre>

**Comment by toprak** [comment]
yes I do get same error.

**Comment by engMaher** [comment]
the installation,post-installation logs seem correct, kindly provide your mail/skype or join gitter chat [support room] to create a live support ticket for this issue [if still exists]

**Comment by toprak** [comment]
@engMaher here is mine toprakbulbulv5@gmail.com
